[0m11:23:54.565107 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACFE0B87A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACFEA8A240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACFDFA2780>]}


============================== 11:23:54.576719 | 09912025-6c89-483d-9187-59886dc95fc9 ==============================
[0m11:23:54.576719 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:23:54.579159 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\vinic\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init datawarehouse', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:23:54.631974 [debug] [MainThread]: Starter project path: C:\Users\vinic\.pyenv\pyenv-win\versions\3.12.7\Lib\site-packages\dbt\include\starter_project
[0m11:23:54.695903 [info ] [MainThread]: 
Your new dbt project "datawarehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:23:54.695903 [info ] [MainThread]: Setting up your profile.
[0m12:36:42.058192 [info ] [MainThread]: Profile datawarehouse written to C:\Users\vinic\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:36:42.066017 [debug] [MainThread]: Command `dbt init` succeeded at 12:36:42.065443 after 4367.84 seconds
[0m12:36:42.068162 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ACFE0B87A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AC80828590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AC80CFCCE0>]}
[0m12:36:42.070752 [debug] [MainThread]: Flushing usage events
[0m12:36:42.779625 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:21:04.265137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029503260B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029502905700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029503038230>]}


============================== 09:21:04.285651 | 01343b9c-4667-46a5-b6eb-772c1797d876 ==============================
[0m09:21:04.285651 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:21:04.287656 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\vinic\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select silver__crm__cust_info', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:21:04.288069 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\vinic\ciencia_de_dados\Projects\DWH_Baara\DWH\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:21:04.289102 [debug] [MainThread]: Command `dbt run` failed at 09:21:04.289102 after 0.24 seconds
[0m09:21:04.290295 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002950234BD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029503260B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295030CDA30>]}
[0m09:21:04.291350 [debug] [MainThread]: Flushing usage events
[0m09:21:04.957479 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:58:43.556858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CB8F74A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252C86CB770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CC40A6C0>]}


============================== 16:58:43.567567 | 2fa9b0cb-e517-412a-8193-16b97a210b76 ==============================
[0m16:58:43.567567 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:58:43.567567 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\vinic\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs serve', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:58:43.569659 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\vinic\ciencia_de_dados\Projects\DWH_Baara\DWH\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:58:43.569659 [debug] [MainThread]: Command `dbt docs serve` failed at 16:58:43.569659 after 0.25 seconds
[0m16:58:43.572170 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CB8F74A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CBDE2600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252CBDE26F0>]}
[0m16:58:43.572170 [debug] [MainThread]: Flushing usage events
[0m16:58:44.263439 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:37:18.929627 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E63CCAF3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E63CEB19D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E63C64AA80>]}


============================== 13:37:18.934867 | 017e4823-508c-4a60-a983-8b8082b1aa82 ==============================
[0m13:37:18.934867 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:37:18.935870 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\vinic\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs serve', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:37:18.936873 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\vinic\ciencia_de_dados\Projects\DWH_Baara\DWH\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:37:18.937885 [debug] [MainThread]: Command `dbt docs serve` failed at 13:37:18.937885 after 0.17 seconds
[0m13:37:18.937885 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E63D1D3830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E63D1D3950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E63D1D3CE0>]}
[0m13:37:18.938883 [debug] [MainThread]: Flushing usage events
[0m13:37:19.623997 [debug] [MainThread]: An error was encountered while trying to flush usage events
